# Generated by Django 2.0.9 on 2018-12-19 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetfile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
