# Generated by Django 2.0.9 on 2018-12-26 03:48

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_auto_20181225_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetfile',
            name='state',
            field=django_fsm.FSMField(choices=[('n', ''), ('p', 'Pending'), ('i', 'In Progress'), ('d', 'Done'), ('a', 'Archived')], default='n', max_length=50),
        ),
    ]
