# Generated by Django 2.0.9 on 2018-12-26 05:58

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_targetfile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='state',
            field=django_fsm.FSMField(choices=[('t', 'TO DO'), ('i', 'In Progress'), ('v', 'Found'), ('f', 'Not Found'), ('e', 'Got Error')], default='t', max_length=50),
        ),
        migrations.AlterField(
            model_name='targetfile',
            name='state',
            field=django_fsm.FSMField(choices=[('n', 'Normal'), ('p', 'Pending'), ('i', 'In Progress'), ('d', 'Done'), ('a', 'Archived')], default='n', max_length=50),
        ),
    ]
