# Generated by Django 2.0.9 on 2018-12-26 10:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0006_auto_20181226_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='state',
            field=django_fsm.FSMField(choices=[('t', 'TO DO'), ('p', 'Pending'), ('i', 'In Progress'), ('v', 'Found'), ('f', 'Not Found'), ('e', 'Got Error')], default='t', max_length=50),
        ),
    ]
