# Generated by Django 2.0.9 on 2019-01-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_auto_20181226_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
