# Generated by Django 2.0.9 on 2018-12-10 20:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip_address', models.CharField(max_length=15)),
                ('port', models.PositiveIntegerField(default=2228, help_text='Port Number of proxy', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('provider', django_fsm.FSMField(choices=[('MPR', 'myprivateproxy.net')], default='MPR', max_length=50)),
                ('state', django_fsm.FSMField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
