# Generated by Django 2.0.9 on 2018-12-10 21:01

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='proxy_type',
            field=django_fsm.FSMField(choices=[('D', 'Dedicated'), ('S', 'Shared')], default='S', max_length=50),
        ),
    ]
