# Generated by Django 2.0.9 on 2018-12-21 05:50

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['modified']},
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='external_plan_id',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='plan_type',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='provider',
            field=django_fsm.FSMField(choices=[('MPR', 'myprivateproxy.net'), ('PNV', 'proxy-n-vpn.com')], default='PNV', max_length=50),
        ),
    ]
