# Generated by Django 2.0.9 on 2018-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_auto_20181221_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
