# Generated by Django 2.0.9 on 2019-02-04 09:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField(unique=True, verbose_name='Article URL')),
                ('state', django_fsm.FSMField(choices=[('r', 'Ready'), ('f', 'Found'), ('n', 'Not Found'), ('d', 'Pending'), ('i', 'In Progress'), ('c', 'Need Confirm'), ('p', 'Page Not Found'), ('e', 'Error')], default='r', max_length=50)),
                ('authors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
