# Generated by Django 2.0.9 on 2019-02-06 10:16

from django.db import migrations


def create_default_buckets(apps, schema_editor):
    Bucket = apps.get_model('articles', 'Bucket')
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        name = "{0}'s default bucket".format(user.username)
        Bucket.objects.create(name=name, user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_buckets)
    ]
