# Generated by Django 2.0.9 on 2019-02-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_default_bucket_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='is_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucket',
            name='job_uuid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
