# Generated by Django 2.0.9 on 2019-02-07 10:14

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190206_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='state',
            field=django_fsm.FSMField(choices=[('r', 'Ready'), ('f', 'Found'), ('n', 'Not Found'), ('d', 'Pending'), ('i', 'In Progress'), ('c', 'Need Confirm'), ('p', 'Page Not Found'), ('b', 'No Author'), ('e', 'Error')], default='r', max_length=50),
        ),
    ]
