# Generated by Django 2.0.9 on 2019-02-21 19:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190207_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('modified',)},
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='job_uuid',
        ),
        migrations.AddField(
            model_name='bucket',
            name='jobs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='Jobs info'),
        ),
    ]
