# Generated by Django 2.0.9 on 2019-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190221_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=500, unique=True, verbose_name='Article URL'),
        ),
    ]
