# Generated by Django 2.0.9 on 2018-12-25 02:53

from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('internal_uuid', models.UUIDField(blank=True, default=None, null=True)),
                ('state', django_fsm.FSMField(choices=[(None, 'Default'), ('i', 'In Progress'), ('p', 'Pending'), ('c', 'Finished'), ('e', 'Got an error')], default=None, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
