# Generated by Django 2.0.9 on 2018-12-26 10:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=django_fsm.FSMField(choices=[('n', 'Default'), ('i', 'In Progress'), ('p', 'Pending'), ('c', 'Finished'), ('e', 'Got an error')], default='n', max_length=50),
        ),
    ]
