# Generated by Django 2.0.9 on 2018-12-27 01:44

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_auto_20181226_1018'),
        ('jobs', '0002_auto_20181226_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='targets.TargetFile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=django_fsm.FSMField(choices=[('n', 'Default'), ('i', 'In Progress'), ('p', 'Pending'), ('c', 'Finished'), ('e', 'Got an error'), ('a', 'Archived')], default='n', max_length=50),
        ),
    ]
