# Generated by Django 2.0.9 on 2019-04-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0004_auto_20190107_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('credential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credentials.Credential')),
            ],
            options={
                'abstract': False,
            },
            bases=('credentials.credential',),
        ),
    ]
