# Generated by Django 2.0.9 on 2018-12-13 14:26

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='email',
            field=models.EmailField(default=None, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='has_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='credential',
            name='proxy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential', to='proxies.Proxy'),
        ),
        migrations.AddField(
            model_name='credential',
            name='recovery_email',
            field=models.EmailField(default='ecmascript.guru@gmail.com', max_length=128),
        ),
        migrations.AddField(
            model_name='credential',
            name='recovery_phone',
            field=models.CharField(default='+8618701401597', max_length=15),
        ),
        migrations.AddField(
            model_name='credential',
            name='state',
            field=django_fsm.FSMField(choices=[('n', 'No proxy'), ('a', 'Active'), ('h', 'Hold'), ('p', 'Processing'), ('u', 'Using')], default='n', max_length=50),
        ),
    ]
