# Generated by Django 2.0.9 on 2018-12-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20181213_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['modified']},
        ),
        migrations.AlterField(
            model_name='credential',
            name='recovery_email',
            field=models.EmailField(default='alexis.leanrank@gmail.com', max_length=128),
        ),
    ]
