# Generated by Django 2.0.9 on 2019-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_auto_20181221_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='captcha_image',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Captcha Image'),
        ),
        migrations.AddField(
            model_name='credential',
            name='captcha_value',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
